# 使用GitHub Pages默认主题 - Cayman
theme: jekyll-theme-cayman
title: "Arxiv论文摘要归档(Brain-inspired AI)"
description: "每日自动检索和总结arXiv论文的工具，使用AI生成论文摘要。本页面的搜索领域固定为脑启发AI（Brain-inspired AI）、神经形态计算、脉冲神经网络等相关领域。"
author: zyxuaan

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  math_engine: nil